# Generated by Django 3.1.7 on 2021-10-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_subject',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
