# Generated by Django 3.1.7 on 2021-10-03 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_message_msg_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg_date',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
